### ISSUE TITLE
New UIImagePickerController feature on iOS11

### ISSUE THREAD

**Issue by erkanyildiz** [KrauseFx/detect.location#6]
> The native image picker built into iOS allows app developers to access the full image library, with all its metadata

On iOS11 this has changed. 
UIImagePickerController runs as a separate process and does not require Photos permission at all. Only the assets user selects on UIImagePickerController gets delivered to the app, in a one-time read-only way. 

https://developer.apple.com/videos/play/wwdc2017/505/

> There should be separate permissions for 

> - `Selecting a photo` (e.g. you want to upload an existing picture to a social network)
> - `Granting full access to the photo library` (e.g. Dropbox or Google Photos to backup your complete library)

The new behaviour on iOS11 is kind of what you (and we all :) ) want. 
For `Selecting a photo` there is no permission at all, as I mentioned above.
From now on, Apple should enforce the use of UIImagePickerController instead of custom image picker UIs.

For `Granting full access to the photo library`, it still works as before.
So, an extra permission layer to access the metadata, as you suggested, would be good.

Thanks.

**Comment by KrauseFx** [comment]
That's awesome, thanks for letting me know 👍  I'll update the post accordingly

**Comment by KrauseFx** [comment]
Just pushed an update, thanks again 🚀 https://github.com/KrauseFx/detect.location/commit/35e1b6e59420f924efebfdacaa5cd09d6437a097

**Comment by bjornworldwide** [comment]
An app shouldn't need permissions to save photos from an app to your photo library (and if it does, it should be specifically just for that).

It's insanely irresponsible on Apple's part that iOS still works this way.
